[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --html=reports/selenium-report.html --self-contained-html
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestWarning
